version: '3.8'
services:
  web-app:
    image: 'python:3.8-buster'
    ports:
      - '${APP_PORT}:8000'
    working_dir: /app
    volumes:
      - '.:/app'
    environment:
      PYTHONDONTWRITEBYTECODE: '1'
      PYTHONUNBUFFERED: '1'
      DB_NAME: '${DB_NAME}'
      DB_PORT: '5432'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
      DB_HOST: db
      REDIS_URI: 'redis://redis:6379/0'
      SECRET_KEY: '${SECRET_KEY}'
      APP_NAME: '${APP_NAME}'
    command:
      - make
      - start
  db:
    image: 'postgres:14-alpine'
    volumes:
      - 'db-data:/var/lib/postgresql'
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_DB: '${DB_NAME}'
  redis:
    image: 'redis:6.2-alpine'
    volumes:
      - 'redis-data:/data'
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - 'pgadmin-data:/var/lib/pgadmin'
    ports:
      - '${PGADMIN_PORT}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_EMAIL}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD}'
volumes:
  db-data: null
  pgadmin-data: null
  redis-data: null
